name: Close Inactive Issues
on: workflow_dispatch

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 448
          days-before-issue-stale: 60
          days-before-issue-close: 0
          close-issue-message: "This issue has been automatically closed due to inactivity. If this issue still applies to you, please comment."
          close-issue-label: inactive
          stale-issue-label:
          any-of-labels: 'bug'
          days-before-pr-stale: -1
          days-before-pr-close: -1
          ascending: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
